language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="django>=1.7,<1.8"

install:
 - pip install -r requirements/test.txt
 - pip install coverage coveralls
 - pip install $DJANGO

script:
  - py.test tests --cov passwords

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.4"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.5"
      env: 
        DJANGO="django>=1.3,<1.4"
    - python: "3.5"
      env: 
        DJANGO="django>=1.4,<1.5"

after_success:
  - coverage report
  - coveralls

notifications:
  email:
    recipients:
      - jacek@ivolution.pl